#!/usr/bin/env ruby

ENV["RAILS_ENV"] ||= ENV["RACK_ENV"] || "development"
ENV["NODE_ENV"] ||= ENV["RAILS_ENV"]

require "parcel-rails"
require "parcel-rails/runner"
Parcel::Rails::Runner.serve(ARGV)
